export const PROFESSIONAL_ROLES = [
  'Médico',
  'Enfermeiro',
  'Fisioterapeuta',
  'Psicólogo',
  'Nutricionista',
  'Fonoaudiólogo',
  'Terapeuta Ocupacional',
  'Dentista',
  'Farmacêutico',
  'Biomédico',
  'Psicopedagogo',
  'Outro',
];

export const MEDICAL_SPECIALTIES = [
  'Acupuntura',
  'Assistência Social',
  'Audiologia',
  'Cardiologia',
  'Clínica Geral',
  'Dermatologia',
  'Disfagia',
  'Educação Física',
  'Endocrinologia',
  'Fisioterapia',
  'Fonoaudiologia Escolar',
  'Fonoaudiologia Infantil',
  'Gastroenterologia',
  'Gerontologia',
  'Ginecologia e Obstetrícia',
  'Infectologia',
  'Linguagem',
  'Motricidade Orofacial',
  'Neurologia',
  'Neuropediatria',
  'Neuropsicologia',
  'Nutrição Clínica',
  'Nutrição Comportamental',
  'Nutrição Esportiva',
  'Nutrição Estética',
  'Nutrição Funcional',
  'Nutrição Hospitalar',
  'Nutrição Materno-Infantil',
  'Oftalmologia',
  'Ortopedia',
  'Pediatria',
  'Psicanálise',
  'Psicologia Clínica',
  'Psicologia Escolar',
  'Psicologia Hospitalar',
  'Psicologia Infantil',
  'Psicologia Organizacional',
  'Psiquiatria',
  'Reabilitação Física',
  'Reumatologia',
  'Saúde Mental',
  'Terapia Cognitiva',
  'Terapia Cognitivo-Comportamental (TCC)',
  'Terapia Ocupacional Hospitalar',
  'Terapia Ocupacional Infantil',
  'Urologia',
  'Voz',
  'Outro',
];
