export const PROFESSIONAL_ROLES = [
    'Médico',
    'Terapeuta Ocupacional',
    'Psicólogo',
    'Fonoaudiólogo',
    'Nutricionista',
    'Biomédico',
    'Enfermeiro',
    'Psicopedadogo'
];

export const MEDICAL_SPECIALTIES = [
    'Acupunturista',
    'Assistente Social',
    'Audiologia',
    'Cardiologista',
    'Clínico Geral',
    'Dermatologista',
    'Disfagia',
    'Educador Físico',
    'Endocrinologista',
    'Fisioterapeuta',
    'Fonoaudiologia Escolar',
    'Fonoaudiologia Infantil',
    'Gastroenterologista',
    'Gerontologia',
    'Ginecologista / Obstetra',
    'Infectologista',
    'Linguagem',
    'Motricidade Orofacial',
    'Neuropediatria',
    'Neurologista',
    'Neuropsicologia',
    'Nutrição Clínica',
    'Nutrição Comportamental',
    'Nutrição Esportiva',
    'Nutrição Estética',
    'Nutrição Funcional',
    'Nutrição Hospitalar',
    'Nutrição Materno-infantil',
    'Oftalmologista',
    'Ortopedista',
    'Pediatra',
    'Psicanálise',
    'Psicologia Clínica',
    'Psicologia Escolar',
    'Psicologia Hospitalar',
    'Psicologia Infantil',
    'Psicologia Organizacional',
    'Psiquiatra',
    'Reabilitação Física',
    'Reumatologista',
    'Saúde Mental',
    'Técnico de Enfermagem',
    'Terapeuta Ocupacional',
    'Terapia Cognitiva',
    'Terapia Cognitivo-Comportamental (TCC)',
    'Terapia Ocupacional Hospitalar',
    'Terapia Ocupacional Infantil',
    'Urologista',
    'Voz'
];
